{% set version = "4.5.4" %}

package:
  name: clingo
  version: {{ version }}

source:
  url: http://downloads.sourceforge.net/project/potassco/clingo/{{ version }}/clingo-{{ version }}-source.tar.gz
  patches:
    - clingo.patch
  
build:
  number: 0

requirements:
  build:
    - scons
    - python
    - tbb
    - bison
    - re2c
  run:
    - python
    - tbb
    - bison
    - re2c

test:
  imports:
    - gringo

about:
  home: http://potassco.sourceforge.net
  license: GPL 3
  summary: Answer Set Programming solver developed at the University of Potsdam, Germany.

extra:
  recipe-maintainers:
    - svidela

