{% set version = "5.0.0" %}

package:
  name: clingo
  version: {{ version }}

source:
  url: https://github.com/potassco/clingo/archive/v{{ version }}.tar.gz
  patches:
    - clingo.patch

build:
  number: 1

requirements:
  build:
    - scons
    - python
    - lua
    - tbb
    - bison
    - re2c
  run:
    - python
    - lua
    - tbb
    - bison
    - re2c

test:
  commands:
    - reify --version
    - gringo --version
    - clingo --version
  imports:
    - clingo

about:
  home: https://potassco.github.io/
  license: GPL3
  summary: Answer Set Programming solver developed at the University of Potsdam, Germany.

extra:
  recipe-maintainers:
    - svidela

