{% set version = "3.0.4" %}

package:
  name: bison
  version: {{ version }}

source:
  fn: bison-{{ version }}.tar.gz
  url: http://ftp.gnu.org/gnu/bison/bison-{{ version }}.tar.gz

build:
  number: 0
  script_env:
   - CC
   - CXX

test:
  commands:
    - bison --help  # [unix]

about:
  home: https://www.gnu.org/software/bison/
  license: GPL 3
  summary: General purpose parser generator converting annotated context-free grammar to a deterministic LR/GLR parser.

extra:
  recipe-maintainers:
    - svidela

